---
kind: pipeline
name: molecule
workspace:
  path: veselahouba.ufw

environment:
  MOLECULE_IMAGES: debian-9 debian-10 ubuntu-16.04 ubuntu-18.04 ubuntu-20.04
steps:
  - name: Lint
    image: veselahouba/molecule
    commands:
      - shellcheck_wrapper
      - flake8
      - yamllint .
      - ansible-lint

  - name: Molecule test
    image: veselahouba/molecule
    environment:
      HCLOUD_TOKEN:
        from_secret: HCLOUD_TOKEN
    commands:
      - ansible --version
      - molecule --version
      # Loop instead of matrix
      - |
        for MOLECULE_IMAGE in $${MOLECULE_IMAGES}; do
          export MOLECULE_IMAGE
          molecule test --all
        done

# ---
# kind: pipeline
# name: release
# depends_on:
#   - molecule
# trigger:
#   event:
#     - tag
# steps:
#   - name: publish
#     image: veselahouba/molecule
#     environment:
#       GALAXY_API_KEY:
#         from_secret: GALAXY_API_KEY
#     commands:
#       - >
#         ansible-galaxy role import --api-key $${GALAXY_API_KEY}
#         $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}
