---
- name: Upload blacklist script
  template:
    src: pull_blacklist.sh
    dest: /opt/pull_blacklist.sh
    owner: root
    group: root
    mode: 0744

- name: Set-up blacklist cron
  cron:
    name: blacklist
    cron_file: blacklist
    user: root
    job: /opt/pull_blacklist.sh {{ ufw_blacklist_url }}
    month: "{{ ufw_blacklist_cron.month|default('*') }}"
    weekday: "{{ ufw_blacklist_cron.weekday|default('*') }}"
    day: "{{ ufw_blacklist_cron.day|default('*') }}"
    hour: "{{ ufw_blacklist_cron.hour|default('*') }}"
    minute: "{{ ufw_blacklist_cron.minute|default('*') }}"
