---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}-srv1
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - server
      - server_open
  - name: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}-srv2
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - server
      - server_closed
  - name: ${REPO_NAME}-${MOLECULE_IMAGE}-${REF}-client
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - client
provisioner:
  name: ansible
verifier:
  name: testinfra
