---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "ufw-${MOLECULE_IMAGE:-debian-10}"
    server_type: cx11
    image: "${MOLECULE_IMAGE:-debian-10}"
provisioner:
  name: ansible
verifier:
  name: testinfra
